# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Blab' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Blab

  pod 'react-native-agora', :path => '../node_modules/react-native-agora'

  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Stripe', '~> 14.0.0'

  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'

end

target 'Blab-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Blab-tvOS

  target 'Blab-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end
